### ISSUE TITLE
Unwanted transition on over

### ISSUE THREAD

**Issue by kuon** [mdgriffith/stylish-elephants#74]
I have the following code:

```elm
El.row [ El.mouseOver
                    [ Font.color (Style.labelBackgroundColor label)
                    , Background.color (Style.labelTextColor label)
                    ]
][]
```

And a `transition` class is added. The problem is because it also adds a transition for `font-size` and this creates unwanted effect when dom node are changed.

For example, I have the following list:

```
----
CATEGORY A
----
result 1
result 2
result 3
----
CATEGORY B
----
result 1
result 2
result 3
``` 

`CATEGORY A` is a header with font size 24, and results are hoverable with font size 16, now the result get a transition class attached, and when I change the result list, and the categories move, for example to the following:

```
----
CATEGORY A
----
result 1
----
CATEGORY B
----
result 1
``` 

The text size is animated in both direction, and it's really weird.

The current workaround is to add some CSS with:

```css
.se.transition {
  transition: none !important;
}


I suggest SE not add any animation or transition that is not explicitly requested.
```
